version: "3.8"
services:
    go-osmand-tracker-map:
        build:
          context: ./web/
          dockerfile: Dockerfile
        volumes:
            - go-osmand-tracker-map:/home/node/go-osmand-tracker/dist

    go-osmand-tracker-api:
        build: .
        ports:
            - 8080:8080
        links:
            - go-osmand-tracker-map
        volumes:
            - go-osmand-tracker-api-db:/go/src/go-osmand-tracker/database/
            - go-osmand-tracker-map:/go/src/go-osmand-tracker/web/dist:ro

volumes:
     go-osmand-tracker-map: {} # The map interface, will be built using yarn and attached to the back-end.
     go-osmand-tracker-api-db: {} # The database files, needs to stay persistent and can also be attached to other services.
