version: "3.8"
services:
    waarzitjenu-map:
        build:
          context: ./web/
          dockerfile: Dockerfile
        volumes:
            - waarzitjenu-map:/home/node/waarzitjenu/map/dist

    waarzitjenu-server:
        build: .
        ports:
            - 8080:8080
        links:
            - waarzitjenu-map
        volumes:
            - waarzitjenu-server-db:/go/src/waarzitjenu/server/database/
            - waarzitjenu-map:/go/src/waarzitjenu/server/web/dist:ro

volumes:
     waarzitjenu-map: {}          # The map interface, will be built using yarn and attached to the back-end.
     waarzitjenu-server-db: {}    # The database files, needs to stay persistent and can also be attached to other services.
