openapi: 3.0.1
info:
  title: go-osmand-tracker
  description: >-
    This is the API specification of the go-osmand-tracker app, an app built to
    receive location updates from the OsmAnd app on iOS and Android devices.
    <br><br> The location tracker is not limited to OsmAnd, it is also possible
    to submit and retrieve location updates from other sources.
  license:
    name: EUPL v1.2
    url: 'https://github.com/ricardobalk/go-osmand-tracker/blob/develop/LICENSE.txt'
  version: 1.1.0
externalDocs:
  description: View the source code on GitHub
  url: 'https://github.com/ricardobalk/go-osmand-tracker'
tags:
  - name: tracking
    description: Submitting and retrieving location updates
paths:
  /submit:
    summary: Submit a location update to the server
    get:
      summary: Submit a single location update (for OsmAnd)
      description: The GET request is used for backwards compatability with the OsmAnd app.
      operationId: ''
      parameters: 
        - name: lat
          in: query
          description: Curreny latitude.
          schema:
            type: number
            format: float64
            example: -4.916161356915467
        - name: lon
          in: query
          description: Curreny lomgitude.
          schema:
            type: number
            format: float64
            example: -160.2222180986629
        - name: timestamp
          in: query
          description: UNIX timestamp with millisecond-precision.
          schema:
            type: integer
            format: uint16
            example: 1602512754000
        - name: hdop
          in: query
          description: Horizontal dilution of precision.
          schema:
            type: number
            format: float64
            example: 1.1547510249347204
        - name: altitude
          in: query
          description: Altitude in meters.
          schema:
            type: number
            format: float64
            example: 134.20841187793522
        - name: speed
          in: query
          description: Speed in m/s.
          schema:
            type: number
            format: float64
            example: 64.77147256992421
      responses:
        '204':
          description: No content. OsmAnd does not need it.
        '401':
          description: Not authenticated.
      tags:
        - tracking
    post:
      summary: Submit a single or multiple location updates (correct REST verb)
      description: ''
      operationId: ''
      requestBody:
          description: 'Single location update'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    latitude:
                      description: Current latitude in decimal degrees.
                      type: number
                      example: -4.916161356915467
                    longitude:
                      description: Current longitude in decimal degrees.
                      type: number
                      example: -160.2222180986629
                    timestamp:
                      description: UNIX timestamp with millisecond-precision.
                      type: number
                      example: 1602512754000
                    hdop:
                      description: Horizontal dilution of precision.
                      type: number
                      example: 1.1547510249347204
                    altitude:
                      description: Current altitude in meters.
                      type: number
                      example: 134.20841187793522
                    speed:
                      description: Current speed in m/s.
                      type: number
                      example: 64.77147256992421
      responses:
        '200':
          description: >-
            Location has been submitted. A response containing the database
            entry is shown.
          content:
            application/json:
              examples:
                Database addition:
                  value: >-
                    [{"ID":102,"Timestamp":1602512754,"Data":{"latitude":-4.916161356915467,"longitude":-160.22221809866299,"timestamp":1602512754,"hdop":1.1547510249347204,"altitude":134.20841187793522,"speed":64.77147256992421}}]
        '401':
          description: Not authenticated.
      tags:
        - tracking
  /retrieve:
    summary: Retrieves location updates
    get:
      summary: Retrieves the last known location
      description: ''
      operationId: ''
      responses:
        '200':
          description: Retrieving last known location(s) successful.
          content:
            application/json:
              examples:
                Single location update:
                  value: >-
                    [{"ID":102,"Timestamp":1602512754,"Data":{"latitude":-4.916161356915467,"longitude":-160.2222180986629,"timestamp":1602512754,"hdop":1.1547510249347204,"altitude":134.20841187793522,"speed":64.77147256992421}}]
                Multiple location updates (using the count parameter):
                  value: >-
                    [{"ID":102,"Timestamp":1602512754,"Data":{"latitude":-4.916161356915467,"longitude":-160.2222180986629,"timestamp":1602512754,"hdop":1.1547510249347204,"altitude":134.20841187793522,"speed":64.77147256992421}},{"ID":101,"Timestamp":1602512754,"Data":{"latitude":33.97124421257169,"longitude":160.0357362345378,"timestamp":1602512754,"hdop":13.786868053846266,"altitude":1681.498893225688,"speed":53.014155880294894}},{"ID":100,"Timestamp":1602512753,"Data":{"latitude":-60.01392249824546,"longitude":98.42609160095583,"timestamp":1602512753,"hdop":14.713819682956101,"altitude":885.1180921964191,"speed":51.32874621010568}}]
        '204':
          description: No location update has been submitted to the database yet.
        '401':
          description: Not authenticated.
      tags:
        - tracking
      parameters:
        - in: query
          name: count
          required: false
          schema:
            type: integer
            format: uint16
            minimum: 1
            maximum: 65535
          description: The number of items to return
servers:
  - url: 'http://localhost:8080/'
    variables: {}


